### ISSUE TITLE
builder appears incompatible with final 4.24.0 release

### ISSUE THREAD

**Issue by wchristian** [ryanjon2040/UE4-Binary-Builder#12]
It appears the changes in #9 weren't sufficient for the final build. This is the error i trace i get trying to build 4.24.0:

```
Welcome to UE4 Binary Builder v2.4
Welcome to UE4 Binary Builder v2.4
Commandline: BuildGraph -target="Make Installed Build Win64" -script=Engine/Build/InstalledEngineBuild.xml -set:WithDDC=true -set:SignExecutables=false -set:EmbedSrcSrvInfo=false -set:GameConfigurations=Development;Shipping -set:WithFullDebugInfo=false -set:HostPlatformDDCOnly=true -set:WithWin64=true -set:WithWin32=false -set:WithMac=false -set:WithAndroid=false -set:WithIOS=false -set:WithTVOS=false -set:WithLinux=false -set:WithSwitch=false -set:WithPS4=false -set:WithXboxOne=false -set:WithLumin=false -set:WithServer=false -set:WithClient=false -set:WithHoloLens=false

Parsing command line: BuildGraph -target="Make Installed Build Win64" -script=Engine/Build/InstalledEngineBuild.xml -set:WithDDC=true -set:SignExecutables=false -set:EmbedSrcSrvInfo=false -set:GameConfigurations=Development;Shipping -set:WithFullDebugInfo=false -set:HostPlatformDDCOnly=true -set:WithWin64=true -set:WithWin32=false -set:WithMac=false -set:WithAndroid=false -set:WithIOS=false -set:WithTVOS=false -set:WithLinux=false -set:WithSwitch=false -set:WithPS4=false -set:WithXboxOne=false -set:WithLumin=false -set:WithServer=false -set:WithClient=false -set:WithHoloLens=false
ERROR: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field not found: 'UnrealBuildTool.UnrealTargetPlatform.HTML5'.
          at HTML5Platform..ctor()
          --- End of inner exception stack trace ---
          at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
          at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
          at System.Activator.CreateInstance(Type type, Boolean nonPublic)
          at System.Activator.CreateInstance(Type type)
          at AutomationTool.Platform.CreatePlatformsFromAssembly(Assembly ScriptAssembly) in c:\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Platform.cs:line 102
          at AutomationTool.Platform.InitializePlatforms(Assembly[] AssembliesWithPlatforms) in c:\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Platform.cs:line 52
          at AutomationTool.ScriptCompiler.FindAndCompileAllScripts(String ScriptsForProjectFileName, List`1 AdditionalScriptsFolders) in c:\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\ScriptCompiler.cs:line 77
          at AutomationTool.Automation.Process(String[] Arguments, StartupTraceListener StartupListener) in c:\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 477
          at AutomationTool.Program.MainProc(String[] Arguments, StartupTraceListener StartupListener) in c:\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 176
          at AutomationTool.Program.<>c__DisplayClass1_0.<Main>b__2() in c:\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 88
          at AutomationTool.InternalUtils.RunSingleInstance(Func`1 Main) in c:\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Utils.cs:line 731
          at AutomationTool.Program.Main(String[] Arguments) in c:\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 88
       (see C:\UnrealEngine\Engine\Programs\AutomationTool\Saved\Logs\Log.txt for full exception trace)
AutomationTool exiting with ExitCode=1 (Error_Unknown)
AutomationToolProcess exited with code 1

==========================BUILD FINISHED==========================
Took 00:00:02
Build ended at Monday, 09 December 2019 18:22:41
```

**Comment by wchristian** [comment]
It appears that this was the result of some files from 4.23 still being in the git repository. My steps were:

  - check out 4.23, run setup.bat, run GenerateProjectFiles.bat
  - use VS to compile automationtool and automationtoollauncher
  - use binary builder to successfully build 4.23
  - fetch newest git, checkout newest release branch
  - retun setup, GenerateProjectFiles
  - start binary builder on 4.24, and it fails

So maybe a good way to handle this would be to catch the specific error seen above and recommend a git clean to "fix" it.
